@startuml bgm-er

entity "**User**" as User {
  +id : String
  --
  name : String
  created_at : LocalDateTime
}

entity "**Bookmark**\n(中間テーブル)" as Bookmark {
  *user_id : String
  *bgm_id : Integer
  --
  created_at : LocalDateTime
}

entity "**Report**" as Report {
+id : Integer
--
*bgm_id : Integer
*reported_by : String
reason : String
created_at : LocalDateTime
}

entity "**Bgm**" as Bgm {
  +id : Integer
  --
  title : String
  url : String
  *created_by : String
  created_at : LocalDateTime
  is_deleted: Boolean
}

entity "**Tag**" as Tag {
  +id : Integer
  --
  title : String
  *created_by : String
  created_at : LocalDateTime
}

entity "**BgmTag**\n(中間テーブル)" as BgmTag {
  *bgm_id : Integer
  *tag_id : Integer
  --
  created_at : LocalDateTime
}

User ||--o{ Bgm
User ||--o{ Bookmark
User ||--o{ Tag
User ||--o{ Report
Bgm  ||--o{ Bookmark
Bgm  ||--o{ BgmTag
Bgm  ||--o{ Report
Tag  ||--o{ BgmTag

@enduml
